export { Config, apply, inject, name } from './plugin.js'
export { parseConfig } from './config.js'
export type { AccessMode, PluginConfig, ResolvedConfig } from './config.js'
export { DeviceStore } from './auth/device-store.js'
export type { DeviceView } from './auth/device-store.js'
export { PairingTokens } from './auth/pairing.js'
export { rewriteAuthenticatedIndex } from './gateway/html.js'
export { LocalGateway } from './gateway/local-gateway.js'
export type { GatewayStatus } from './gateway/local-gateway.js'
export { allowedGatewayHost, isPrivateAddress, privateInterfaceAddresses } from './network.js'
